name: flappy_bird
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  lottie:
  http:
  path_provider:
  rating_dialog:
  audioplayers:
  win32:
  archive:
  smooth_star_rating_null_safety:
  share_plus:
  hive:
  hive_flutter:
  firebase_crashlytics:

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_lints:
  flutter_launcher_icons:
  video_player:
  firebase_core:
  firebase_auth:
  firebase_database:
  change_app_package_name:
  in_app_update:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/pics/icon.png"
  adaptive_icon_foreground: "assets/pics/icon.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - assets/pics/
    - assets/audio/
  fonts:
    - family: Magic4
      fonts:
        - asset: assets/fonts/DiloWorld-mLJLv.ttf
    - family: FlappyBirdy
      fonts:
        - asset: assets/fonts/FlappybirdyRegular-KaBW.ttf
    - family: JungleAdventurer
      fonts:
        - asset: assets/fonts/JungleAdventurer.ttf